package main

import "testing"

func lines(pairs ...[2]string) []addedLine {
	var out []addedLine
	for i, p := range pairs {
		out = append(out, addedLine{file: p[0], line: string(rune('1' + i)), text: p[1]})
	}
	return out
}

func allExist(string) bool  { return true }
func noneExist(string) bool { return false }

// ── the ratchet ─────────────────────────────────────────────────────────────

func TestProseWithoutTests_ExceedsTheRatchet(t *testing.T) {
	r := evaluate(lines(
		[2]string{"internal/x.go", "// this explains a thing"},
		[2]string{"internal/x.go", "// and another thing"},
	), allExist)
	if r.comments != 2 || r.testLines != 0 {
		t.Fatalf("expected 2 prose / 0 test, got %d/%d", r.comments, r.testLines)
	}
}

// The control: the same prose alongside test lines is within budget.
func TestProseAccompaniedByTests_IsWithinBudget(t *testing.T) {
	r := evaluate(lines(
		[2]string{"internal/x.go", "// this explains a thing"},
		[2]string{"internal/x_test.go", "\tif got != want { t.Fatal() }"},
		[2]string{"internal/x_test.go", "\tgot := f()"},
	), allExist)
	if r.comments != 1 || r.testLines != 2 {
		t.Fatalf("expected 1 prose / 2 test, got %d/%d", r.comments, r.testLines)
	}
	if r.comments > r.testLines {
		t.Fatal("prose accompanied by more test lines must not exceed the ratchet")
	}
}

// ── the claim rule ──────────────────────────────────────────────────────────

func TestClaimInProductionCode_IsFlagged(t *testing.T) {
	r := evaluate(lines([2]string{"cmd/server/main.go", "// this never runs because auth 401s first"}), allExist)
	if len(r.claims) != 1 {
		t.Fatalf("an added comment asserting behaviour must be flagged; got %d. This exact "+
			"comment shipped in artifact-api and was false: it hid a missing scope gate.", len(r.claims))
	}
}

func TestClaimNamingItsProof_IsAccepted(t *testing.T) {
	r := evaluate(lines([2]string{"cmd/server/main.go", "// never served unauthorised. proven-by: TestGate"}), allExist)
	if len(r.claims) != 0 {
		t.Fatalf("a claim naming a proof must be accepted; got %d claims", len(r.claims))
	}
}

// A test file IS the proof, so a header stating what it proves is the shape we
// want rather than the shape being policed.
func TestClaimInsideATestFile_IsExempt(t *testing.T) {
	r := evaluate(lines([2]string{"internal/x_test.go", "// the gate must refuse an unscoped token"}), allExist)
	if len(r.claims) != 0 || r.comments != 0 {
		t.Fatalf("claims in test files are exempt and not counted; got %d claims, %d prose", len(r.claims), r.comments)
	}
}

// Recording the wrong comment you are deleting must not be punished.
func TestQuotedClaim_IsReportingNotAsserting(t *testing.T) {
	r := evaluate(lines([2]string{"cmd/server/main.go", `// the old comment said "this never runs" which was untrue`}), allExist)
	if len(r.claims) != 0 {
		t.Fatalf("a claim inside quotes is being reported, not made; got %d", len(r.claims))
	}
}

// ── functional directives ───────────────────────────────────────────────────

func TestFunctionalDirectives_AreNotProse(t *testing.T) {
	for _, d := range []string{
		"//go:build unit",
		"//nolint:gosec // rationale",
		"// Code generated by mockery. DO NOT EDIT.",
		"#!/usr/bin/env bash",
		"# renovate: datasource=docker",
		"// @Success 200 {object} map[string]string",
		"-- +goose Up",
	} {
		r := evaluate(lines([2]string{"internal/x.go", d}), allExist)
		if r.comments != 0 {
			t.Errorf("%q instructs a tool and cannot be a false claim; must not count as prose", d)
		}
	}
}

// ── proven-by must be verifiable ────────────────────────────────────────────

func TestProvenByNamingSomethingAbsent_IsFlagged(t *testing.T) {
	r := evaluate(lines([2]string{"preview/x.yaml", "# proven-by: 17-scope-semantics.sh"}), noneExist)
	if len(r.dangling) != 1 {
		t.Fatalf("a proven-by naming something absent must be flagged; got %d. This happened: "+
			"the script named lived in another repo, so this repo's CI could never run it and "+
			"the reference could rot exactly like prose.", len(r.dangling))
	}
}

// ── diff parsing ────────────────────────────────────────────────────────────

func TestParseDiff_AttributesLinesToFilesAndNumbers(t *testing.T) {
	fixture := "diff --git a/x.go b/x.go\n" +
		"--- a/x.go\n+++ b/x.go\n" +
		"@@ -10,0 +11,2 @@\n" +
		"+// first added line\n" +
		"+// second added line\n" +
		"--- a/y_test.go\n+++ b/y_test.go\n" +
		"@@ -1,0 +5,1 @@\n" +
		"+\tt.Fatal(\"x\")\n"

	got, err := parseDiff(fixture)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 3 {
		t.Fatalf("expected 3 added lines, got %d — the parser is broken, and a broken "+
			"parser reports a clean gate on a dirty diff", len(got))
	}
	if got[0].file != "x.go" || got[0].line != "11" {
		t.Errorf("first line mis-attributed: %+v", got[0])
	}
	if got[2].file != "y_test.go" || got[2].line != "5" {
		t.Errorf("test-file line mis-attributed: %+v", got[2])
	}
}

// Anchor: a diff with no additions must yield nothing, not silently succeed on
// a parse that dropped everything.
func TestParseDiff_EmptyDiffYieldsNothing(t *testing.T) {
	got, err := parseDiff("")
	if err != nil || len(got) != 0 {
		t.Fatalf("empty diff must yield no lines; got %d, err=%v", len(got), err)
	}
}

// An indented block quote of output records what a tool printed. The claim
// words in it are the tool's, not the author's — flagging them would punish
// pasting the error you are fixing.
func TestIndentedBlockQuoteOfOutput_IsNotAClaim(t *testing.T) {
	for _, q := range []string{
		"#   FAIL: preview never reached stable ready state",
		"//   Error: ingresses.networking.k8s.io already exists",
		"#     scope=<disallowed> -> 400 invalid_scope, no token is ever issued",
	} {
		r := evaluate(lines([2]string{"preview/x.yaml", q}), allExist)
		if len(r.claims) != 0 {
			t.Errorf("%q is quoted output, not an assertion; got %d claims", q, len(r.claims))
		}
	}
}

// TestPatternListCommentsAreNotProse keeps a hygiene change from being
// unable to explain itself.
//
// The ratio rule fails when prose exceeds test lines, so with zero tests ANY
// comment fails. A .gitignore commit legitimately has no tests, and
// leartech-go-service-template #149 and leartech-maestro-service #13 both
// stalled on five lines naming which artifacts were being ignored and why.
//
// The exemption has to stay narrow, so this also pins what is NOT exempt.
func TestPatternListCommentsAreNotProse(t *testing.T) {
	exempt := []addedLine{
		{file: ".gitignore", text: "# end2end run artifacts, written by run.sh"},
		{file: "some/dir/.gitignore", text: "# vendored deps"},
		{file: ".dockerignore", text: "# build context noise"},
		{file: ".gitattributes", text: "# normalise line endings"},
	}
	r := evaluate(exempt, func(string) bool { return true })
	if r.comments != 0 {
		t.Errorf("counted %d prose line(s) in pattern-list files; a .gitignore comment "+
			"labels globs and has no behaviour to prove", r.comments)
	}
	if len(r.claims) != 0 {
		t.Errorf("flagged %d claim(s) in pattern-list files", len(r.claims))
	}

	// Not exempt: anything that describes behaviour.
	counted := []addedLine{
		{file: "values.yaml", text: "# the issuer must be reachable"},
		{file: "main.go", text: "// callers must hold the lock"},
		{file: "gitignore.md", text: "# not a pattern list at all"},
		{file: "internal/.gitignore.go", text: "// a go file that merely mentions gitignore"},
	}
	r2 := evaluate(counted, func(string) bool { return true })
	if r2.comments != len(counted) {
		t.Errorf("counted %d of %d prose lines outside pattern-list files; the exemption "+
			"has leaked beyond the three filenames it names", r2.comments, len(counted))
	}
}
