apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: preview-copy-secrets
spec:
  stepTemplate:
    env:
      - name: HOME
        value: /tekton/home
    envFrom:
      - secretRef:
          name: jx-boot-job-env-vars
          optional: true
    name: ""
    resources: {}
    workingDir: /workspace/source
  steps:
    - image: jx3mqubebuild.azurecr.io/ghcr-io/jenkins-x-plugins/jx-promote:0.6.28
      name: copy-secrets
      resources: {}
      script: |
        #!/usr/bin/env sh
        source /workspace/source/.jx/variables.sh
        jx secret copy --create-namespace --selector "secret.jenkins-x.io/replica-source=true" -n preview-secrets --to jx-$REPO_OWNER-$APP_NAME-pr-$PULL_NUMBER
  workspaces:
    - description: Copy secrets into the preview namespace
      mountPath: /workspace
      name: output
